CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    requested_rounds INTEGER NOT NULL CHECK (requested_rounds > 0),
    completed_rounds INTEGER NOT NULL CHECK (completed_rounds >= 0)
);

CREATE TABLE game_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    seat_number INTEGER NOT NULL CHECK (seat_number >= 0),
    final_score INTEGER NOT NULL CHECK (final_score >= 0),
    winner BOOLEAN NOT NULL,
    CONSTRAINT fk_game_players_game
        FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
    CONSTRAINT fk_game_players_player
        FOREIGN KEY (player_id) REFERENCES players(id),
    CONSTRAINT uq_game_players_seat UNIQUE (game_id, seat_number),
    CONSTRAINT uq_game_players_player UNIQUE (game_id, player_id)
);

CREATE TABLE rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    round_number INTEGER NOT NULL CHECK (round_number > 0),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL,
    winner_player_id BIGINT,
    awarded_points INTEGER NOT NULL CHECK (awarded_points >= 0),
    CONSTRAINT fk_rounds_game
        FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
    CONSTRAINT fk_rounds_winner
        FOREIGN KEY (winner_player_id) REFERENCES players(id),
    CONSTRAINT uq_rounds_number UNIQUE (game_id, round_number)
);

CREATE TABLE round_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    score_before INTEGER NOT NULL CHECK (score_before >= 0),
    score_delta INTEGER NOT NULL CHECK (score_delta >= 0),
    score_after INTEGER NOT NULL CHECK (score_after >= 0),
    CONSTRAINT fk_round_scores_round
        FOREIGN KEY (round_id) REFERENCES rounds(id) ON DELETE CASCADE,
    CONSTRAINT fk_round_scores_player
        FOREIGN KEY (player_id) REFERENCES players(id),
    CONSTRAINT uq_round_scores_player UNIQUE (round_id, player_id)
);

CREATE INDEX idx_games_completed_at ON games(completed_at DESC);
CREATE INDEX idx_game_players_score ON game_players(final_score DESC);
CREATE INDEX idx_game_players_winner ON game_players(player_id, winner);
